- name: Ejecutar Script de Python
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DB_INGRESOS: ${{ secrets.DB_INGRESOS }}
          DB_EGRESOS: ${{ secrets.DB_EGRESOS }}
        run: python main.py
